export const articles = [
    {
        id: 1,
        title: "Understanding React Hooks",
        author: "John Doe",
        date: "2024-10-15",
        popularity: 150,
        excerpt: "An in-depth look at React hooks and how they can improve your component logic...",
        topic: "technology",
        profileImg:"https://easy-peasy.ai/cdn-cgi/image/quality=80,format=auto,width=700/https://fdczvxmwwjwpwbeeqcth.supabase.co/storage/v1/object/public/images/d664ddb1-a0c9-41cb-8ad7-53e323e5502d/e9df037a-8347-417b-af5c-0332420122df.png"
    },
    {
        id: 2,
        title: "The Science Behind Climate Change",
        author: "Alice Smith",
        date: "2024-09-23",
        popularity: 200,
        excerpt: "Exploring the evidence and science behind climate change and its global impact...",
        topic: "science",
        profileImg:"https://media.gettyimages.com/id/1317804578/photo/one-businesswoman-headshot-smiling-at-the-camera.jpg?s=612x612&w=gi&k=20&c=tFkDOWmEyqXQmUHNxkuR5TsmRVLi5VZXYm3mVsjee0E="
    },
    {
        id: 3,
        title: "Health Benefits of a Plant-Based Diet",
        author: "Mary Johnson",
        date: "2024-08-10",
        popularity: 250,
        excerpt: "Learn about the numerous health benefits associated with adopting a plant-based diet...",
        topic: "health",
        profileImg:"https://c8.alamy.com/comp/KEDB24/handsome-young-man-profile-KEDB24.jpg"
    },
    {
        id: 4,
        title: "Artificial Intelligence in Modern Healthcare",
        author: "David Brown",
        date: "2024-07-20",
        popularity: 300,
        excerpt: "An exploration of how AI is transforming the healthcare industry with new solutions...",
        topic: "technology",
         profileImg:"https://easy-peasy.ai/cdn-cgi/image/quality=80,format=auto,width=700/https://fdczvxmwwjwpwbeeqcth.supabase.co/storage/v1/object/public/images/d664ddb1-a0c9-41cb-8ad7-53e323e5502d/e9df037a-8347-417b-af5c-0332420122df.png"
    },
    {
        id: 5,
        title: "Advancements in Quantum Computing",
        author: "Sophia Liu",
        date: "2024-06-05",
        popularity: 400,
        excerpt: "An overview of the current state of quantum computing and its future potential...",
        topic: "science",
         profileImg:"https://easy-peasy.ai/cdn-cgi/image/quality=80,format=auto,width=700/https://fdczvxmwwjwpwbeeqcth.supabase.co/storage/v1/object/public/images/d664ddb1-a0c9-41cb-8ad7-53e323e5502d/e9df037a-8347-417b-af5c-0332420122df.png"
    },
    {
        id: 6,
        title: "Mental Health Awareness in the Digital Age",
        author: "James White",
        date: "2024-05-22",
        popularity: 180,
        excerpt: "How digital platforms are affecting mental health and what we can do about it...",
        topic: "health",
         profileImg:"https://easy-peasy.ai/cdn-cgi/image/quality=80,format=auto,width=700/https://fdczvxmwwjwpwbeeqcth.supabase.co/storage/v1/object/public/images/d664ddb1-a0c9-41cb-8ad7-53e323e5502d/e9df037a-8347-417b-af5c-0332420122df.png"
    },
    {
        id: 7,
        title: "Exploring Renewable Energy Sources",
        author: "Emma Green",
        date: "2024-04-30",
        popularity: 220,
        excerpt: "A comprehensive guide to renewable energy sources and their benefits...",
        topic: "science",
    },
    {
        id: 8,
        title: "5G Technology and Its Impact on Connectivity",
        author: "Michael Brown",
        date: "2024-03-15",
        popularity: 270,
        excerpt: "Understanding the advancements and challenges in the rollout of 5G technology...",
        topic: "technology",
    },
    {
        id: 9,
        title: "The Importance of Cybersecurity in 2024",
        author: "Jessica Turner",
        date: "2024-02-10",
        popularity: 350,
        excerpt: "Exploring the growing need for cybersecurity measures in an interconnected world...",
        topic: "technology",
    },
    {
        id: 10,
        title: "COVID-19: Lessons Learned and Future Preparedness",
        author: "Daniel Clark",
        date: "2024-01-12",
        popularity: 420,
        excerpt: "Analyzing the global response to COVID-19 and how we can better prepare for pandemics...",
        topic: "health",
    },
    {
        id: 11,
        title: "The Future of Electric Vehicles",
        author: "Sarah Lee",
        date: "2023-12-28",
        popularity: 310,
        excerpt: "Examining the advancements in electric vehicle technology and adoption trends...",
        topic: "science",
    },
    {
        id: 12,
        title: "Blockchain Beyond Cryptocurrency",
        author: "Ethan Kim",
        date: "2023-11-18",
        popularity: 295,
        excerpt: "Understanding the potential of blockchain technology across various industries...",
        topic: "technology",
    },
    {
        id: 13,
        title: "Nutrition Myths and Facts",
        author: "Emily Wong",
        date: "2023-10-10",
        popularity: 230,
        excerpt: "Debunking common myths about nutrition and highlighting important health facts...",
        topic: "health",
    },
    {
        id: 14,
        title: "How Technology is Changing Education",
        author: "Liam Scott",
        date: "2023-09-15",
        popularity: 290,
        excerpt: "An exploration of how digital tools and platforms are transforming the learning process...",
        topic: "technology",
    },
    {
        id: 15,
        title: "The Role of Genetics in Personalized Medicine",
        author: "Olivia Davis",
        date: "2023-08-24",
        popularity: 320,
        excerpt: "How genetic research is shaping the future of personalized healthcare...",
        topic: "science",
    }
];
